---
strategy: webhook
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://promptink-production.up.railway.app/api/trmnl/webhook/1
polling_headers: ''
polling_body: ''
id: 221038
custom_fields:
- keyname: image_url
  name: Image URL
  field_type: text
- keyname: has_image
  name: Has Image
  field_type: text
- keyname: prompt
  name: Prompt
  field_type: text
- keyname: background_color
  name: Background Color
  field_type: text
- keyname: updated_at
  name: Updated At
  field_type: text
name: PromptInk
refresh_interval: 15
